# Generated by Django 3.1.5 on 2021-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField()),
                ('date_synced', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
