# Generated by Django 3.1.5 on 2021-02-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_created',
            field=models.DateTimeField(unique=True),
        ),
    ]
