# Generated by Django 3.1.5 on 2021-02-04 23:06

from django.db import migrations
from django.db.migrations import RunPython


def remove_workouts(apps, schema_editor):
    # remove workouts since we're adding a unique ifit id on them
    Workout = apps.get_model("sync", "Workout")
    Workout.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20210204_2028'),
    ]

    operations = [
        RunPython(remove_workouts)
    ]
