# Generated by Django 3.1.5 on 2021-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20210204_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='workout',
            name='ifit_id',
            field=models.CharField(default='FAKE', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
