version: '2'

services:
  ifit:
    build: .
    ports:
      - "8080:80"
    restart: always
    env_file:
      - env
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
      REDIS_URL: "redis://redis"
    depends_on:
      - redis
      - postgres

  celery:
    build: .
    restart: always
    env_file:
      - env
    entrypoint: celery -A sync worker --beat --loglevel INFO
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
      REDIS_URL: "redis://redis"
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ifit-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  ifit-postgresql:
